# Generated by Django 2.2.5 on 2020-07-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('UserName', models.CharField(max_length=300)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
