# Generated by Django 2.2.5 on 2020-08-02 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200729_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=300)),
                ('Password', models.IntegerField()),
                ('FullName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user1',
        ),
    ]
