# Generated by Django 2.2.5 on 2020-08-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200803_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.login'),
        ),
    ]
