# Generated by Django 2.2.5 on 2020-08-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200803_0254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='',
        ),
    ]
